import React from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  useWindowDimensions,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Stack, useRouter } from 'expo-router';
import { TouchableOpacity } from 'react-native';
import { colors, spacing } from '../src/theme';
import { PRIVACY_POLICY_LAST_UPDATED } from '../src/constants/legal';

export default function PrivacyPolicyScreen() {
  const router = useRouter();
  const { width } = useWindowDimensions();
  const isWide = width >= 768;

  return (
    <SafeAreaView style={styles.safe}>
      <Stack.Screen options={{ headerShown: false }} />
      <ScrollView
        contentContainerStyle={[styles.scroll, isWide && styles.scrollWide]}
        showsVerticalScrollIndicator={false}
      >
        <TouchableOpacity onPress={() => router.back()} style={styles.back}>
          <Text style={styles.backText}>← Back</Text>
        </TouchableOpacity>

        <Text style={styles.h1}>Privacy Policy</Text>
        <Text style={styles.meta}>Aviation Job Talent · Last updated: {PRIVACY_POLICY_LAST_UPDATED}</Text>

        <Section title="1. Who we are">
          <P>
            Aviation Job Talent is operated by <Bold>[LEGAL_ENTITY_NAME]</Bold>, registered at
            {' '}<Bold>[LEGAL_ADDRESS]</Bold>. We connect aviation maintenance technicians with aviation companies, MROs, airlines, operators and recruiters.
          </P>
          <P>
            For privacy enquiries contact: <Bold>management@rotoraxisconsulting.com</Bold>
          </P>
        </Section>

        <Section title="2. Data we collect">
          <P><Bold>Technicians</Bold></P>
          <BulletList items={[
            'Full name, email address, optional phone number and date of birth. Date of birth is retained as account-eligibility information and is not shared with companies.',
            'Profile and professional information: technician types, selected country and optional city, availability, contract preferences, years of experience, licences, issue and expiry dates, aircraft type ratings and optional professional links.',
            'Documents and file metadata you choose to upload, including PDFs or images of aviation licences, medical certificates, training records, identity documents, resumes and other supporting records.',
            'Applications, direct-offer responses, connection status and cover notes.',
            'Chat messages with companies after a connection is accepted.',
          ]} />
          <P><Bold>Company users</Bold></P>
          <BulletList items={[
            'Account or team-member name, work email address, user role and account identifier.',
            'Company information: name, type, selected country and optional city, email address, optional phone number and optional website.',
            'Job offers and requirements you create, including descriptions, locations, contract details and required credentials.',
            'Applications, direct offers, responses and connection status.',
            'Chat messages with technicians after a connection is accepted.',
          ]} />
          <P><Bold>All users</Bold></P>
          <BulletList items={[
            'Account identifiers, role, account status and verification status.',
            'Authentication credentials (email and password authentication managed by Supabase Auth; we do not store readable passwords).',
            'Timestamps of consent to these Terms and this Privacy Policy.',
            'Marketplace activity records needed to deliver applications, direct offers, chats, unread indicators and status updates.',
            'City-directory search terms and country filters sent when you search for a city, plus any free-text catalogue request you submit.',
            'Authentication and security logs generated by our infrastructure provider, which can include user ID, IP address, user agent, event type and timestamp.',
            'Optional account-deletion feedback. It is stored separately without an account identifier; free-text feedback could still contain information you choose to enter.',
          ]} />
          <P>
            Location is supplied by the user as a country and, optionally, a city. The app does not request GPS location, contacts, microphone access or advertising identifiers.
          </P>
        </Section>

        <Section title="3. How we use your data">
          <BulletList items={[
            'To create and manage accounts, sessions, profiles and company teams.',
            'To operate the matching platform: display technician profiles without direct identifiers to companies and match them to job offers.',
            'To verify professional credentials via admin review.',
            'To facilitate communication between technicians and companies after an accepted connection.',
            'To deliver applications, direct offers, activity indicators and their current status.',
            'To enforce platform security (rate-limiting, fraud prevention).',
            'To improve the service using optional account-deletion feedback.',
            'To comply with legal obligations.',
          ]} />
        </Section>

        <Section title="4. Privacy by default — technician identity">
          <P>
            Technician identity is <Bold>private by default</Bold>. Companies can only see an anonymous code, country, city, licences, aircraft types, availability, years of experience, verification status and match score.
          </P>
          <P>
            Full name, email address, phone number and professional links are <Bold>never visible to companies</Bold> until both parties have accepted a connection (application accepted or direct offer accepted).
          </P>
          <P>
            After acceptance, the connected company can also access verified professional documents such as licences, training records and resumes. Medical certificates and identity documents are excluded.
          </P>
          <P>
            Medical certificates and identity documents are <Bold>exclusively reviewed by our admin team</Bold> for verification purposes. They are never shared with companies in any form.
          </P>
        </Section>

        <Section title="5. Special categories — medical data (GDPR Art. 9)">
          <P>
            Medical certificates (EASA Class 1/2/3, FAA AME) constitute health data under GDPR Article 9. We process this data exclusively:
          </P>
          <BulletList items={[
            'On the basis of your explicit consent, given at the time of upload.',
            'For the purpose of professional licence verification by our admin team.',
            'The medical certificate file and its metadata are not accessible to companies.',
          ]} />
          <P>
            Aviation Job Talent is not a medical device and does not diagnose, treat, cure or prevent any medical condition. The certificate is used only as a professional credential supplied voluntarily by the technician.
          </P>
          <P>
            You may withdraw this consent at any time by asking us to delete the medical document or by deleting your account. Withdrawal does not affect processing already carried out on the basis of valid consent.
          </P>
        </Section>

        <Section title="6. Legal basis for processing (GDPR)">
          <BulletList items={[
            'Contract (Art. 6(1)(b)): to provide the platform service you signed up for.',
            'Legitimate interest (Art. 6(1)(f)): platform security, fraud prevention, service improvement.',
            'Legal obligation (Art. 6(1)(c)): compliance with applicable law.',
            'Explicit consent (Art. 9(2)(a)): medical data processing.',
          ]} />
        </Section>

        <Section title="7. Data sharing">
          <P>We do not sell your personal data. We share data only with:</P>
          <BulletList items={[
            'Supabase and its configured subprocessors, which provide database hosting, file storage, authentication, realtime messaging, security logging and related infrastructure.',
            'Companies using the Platform: a privacy-limited technician profile without direct identifiers before acceptance, and the identity and permitted professional contact information of the technician only after the relevant application or direct offer is accepted.',
            'Technicians using the Platform: company profiles, published offers and messages needed to use the marketplace.',
            'countries.dev, which provides the GeoNames-based city directory and receives the city search term, country filter and ordinary network request data.',
            'OpenStreetMap Foundation tile services, which receive requested map-tile coordinates and ordinary network request data such as IP address and user agent when a map is displayed.',
            'jsDelivr, unpkg and FlagCDN, which deliver map libraries, styles or flag images and receive ordinary network request data when those resources are loaded.',
            'Legal authorities: only when required by law.',
          ]} />
          <P>
            These external directory, map and content-delivery providers process requests under their own privacy terms. We make those requests to deliver the feature you selected and do not use them for advertising; each provider's own use and retention are governed by its terms.
          </P>
          <P>
            We do not share data with advertising networks or data brokers, and we do not use personal data for cross-app or cross-site tracking.
          </P>
        </Section>

        <Section title="8. Data retention">
          <BulletList items={[
            'Active accounts: data retained while your account is active.',
            'Deleted technician accounts: names, contact details, authentication credentials, document rows and uploaded files are removed when deletion completes. A limited marketplace record can retain the original internal account identifier, an anonymous display code, coarse location, professional qualifications, availability, verification state and relationship history for platform integrity. The identifier is not shown as contact information, but it and combinations of specialist professional details mean the retained record is pseudonymous and may remain indirectly identifying.',
            'Deleted company-member accounts: names, contact details, membership and authentication credentials are removed. The original internal account identifier can remain in a limited deleted-account record and retained message-sender references after message content is replaced. Company profiles, offers and marketplace records can remain where needed for other company members and platform integrity. The retained identifier is not displayed as contact information, but it means the remaining record is pseudonymous rather than anonymous.',
            'Documents: removed from storage when account deletion completes or when we complete a verified document-deletion request.',
            'Authentication and security logs: retained for limited periods according to our infrastructure configuration and legitimate security needs.',
            'Invitation and rate-limit records: retained for security and abuse prevention according to operational need.',
            'Exit survey: if you choose to tell us why you are leaving, the stored row has no account ID and uses only your role and calendar day. Free text or a low number of deletions on that day can still make a response indirectly identifiable. It is kept to improve the service. Answering is optional and deletion never depends on it.',
          ]} />
        </Section>

        <Section title="9. Your rights (GDPR)">
          <P>If you are in the European Economic Area you have the right to:</P>
          <BulletList items={[
            'Access: request a copy of your personal data.',
            'Rectification: correct inaccurate data.',
            'Erasure: request deletion of your data ("right to be forgotten").',
            'Restriction: limit processing of your data.',
            'Portability: receive your data in a machine-readable format.',
            'Object: object to processing based on legitimate interests.',
            'Withdraw consent: withdraw consent for medical data processing at any time.',
          ]} />
          <P>
            To exercise any right, contact: <Bold>management@rotoraxisconsulting.com</Bold>{'\n'}
            You also have the right to lodge a complaint with your local supervisory authority.
          </P>
        </Section>

        <Section title="10. Account deletion">
          <P>
            You can initiate account deletion from <Bold>Settings → Delete account</Bold> inside the app. See also the <Bold>/delete-account</Bold> page for step-by-step instructions.
          </P>
          <P>
            A sole company administrator is currently asked to assign another administrator first so the company record is not orphaned. If that is not possible, contact support to arrange deletion and decide how the company record should be handled.
          </P>
        </Section>

        <Section title="11. Cookies and tracking">
          <P>
            The mobile app does not use cookies. The web version uses only local session storage or technically necessary storage for authentication. We do not currently include advertising, attribution or third-party analytics SDKs, and we do not track users across apps or websites.
          </P>
        </Section>

        <Section title="12. Security">
          <P>
            We use TLS for data in transit. Authentication is handled by Supabase Auth, private documents are stored in a non-public bucket, and row-level security policies limit access to authorised users.
          </P>
        </Section>

        <Section title="13. Changes to this policy">
          <P>
            We will publish updates to this policy and notify users of material changes where required. If a change requires new consent, we will ask for it before carrying out that processing.
          </P>
        </Section>

        <Section title="14. Contact">
          <P>
            General support: <Bold>support@aviationjobtalent.com</Bold>{'\n'}
            Privacy enquiries: <Bold>management@rotoraxisconsulting.com</Bold>{'\n'}
            Legal entity: <Bold>[LEGAL_ENTITY_NAME]</Bold>{'\n'}
            Address: <Bold>[LEGAL_ADDRESS]</Bold>
          </P>
        </Section>
      </ScrollView>
    </SafeAreaView>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <View style={styles.section}>
      <Text style={styles.h2}>{title}</Text>
      {children}
    </View>
  );
}

function P({ children }: { children: React.ReactNode }) {
  return <Text style={styles.p}>{children}</Text>;
}

function Bold({ children }: { children: React.ReactNode }) {
  return <Text style={styles.bold}>{children}</Text>;
}

function BulletList({ items }: { items: string[] }) {
  return (
    <View style={styles.bulletList}>
      {items.map((item, i) => (
        <View key={i} style={styles.bulletRow}>
          <Text style={styles.bulletDot}>•</Text>
          <Text style={styles.bulletText}>{item}</Text>
        </View>
      ))}
    </View>
  );
}

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.background },
  scroll: {
    padding: spacing.lg,
    paddingBottom: spacing.xxxl,
  },
  scrollWide: {
    maxWidth: 720,
    width: '100%',
    alignSelf: 'center',
  },
  back: { paddingVertical: spacing.sm, alignSelf: 'flex-start', marginBottom: spacing.sm },
  backText: { color: colors.blue, fontSize: 14, fontWeight: '500' },
  h1: {
    fontSize: 28,
    fontWeight: '700',
    color: colors.text,
    marginBottom: spacing.xs,
  },
  meta: {
    fontSize: 12,
    color: colors.textMuted,
    marginBottom: spacing.xl,
  },
  section: { marginBottom: spacing.xl },
  h2: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.text,
    marginBottom: spacing.sm,
  },
  p: {
    fontSize: 14,
    color: colors.textSecondary,
    lineHeight: 22,
    marginBottom: spacing.sm,
  },
  bold: { fontWeight: '700', color: colors.text },
  bulletList: { gap: spacing.xs, marginBottom: spacing.sm },
  bulletRow: { flexDirection: 'row', alignItems: 'flex-start', gap: spacing.xs },
  bulletDot: { color: colors.blue, fontSize: 14, width: 14, marginTop: 3 },
  bulletText: { flex: 1, fontSize: 14, color: colors.textSecondary, lineHeight: 22 },
});
