-- ============================================================
-- RotoraxisMatch V2 — Supabase/Postgres Schema
-- ============================================================
-- CLEAN-START POLICY:
--   Run this file on a fresh Supabase project.
--   It contains: enums, CREATE TABLE statements, catalog INSERTs
--   (technician_types, license_categories, aircraft_types,
--    company_types, contract_types).
--
--   It does NOT contain: local demo seed data.
--   Local demo JSON seeds (src/data/seeds/) use human-readable IDs
--   (tech-001, comp-001, etc.) that are NOT valid Supabase UUIDs.
--   Those seeds exist only for local AsyncStorage/demo mode and must
--   NOT be inserted into a Supabase database.
--
-- After running this file:
--   1. Create the first admin user in Supabase Auth.
--   2. Run docs/V2_S1_ADMIN_BOOTSTRAP_SQL.sql to insert the admin
--      profile row (profiles.id = auth.users.id).
--   3. Register real users via Supabase Auth — all IDs come from
--      auth.uid() and are generated by Postgres (gen_random_uuid()).
--
-- No destructive SQL included.
-- ============================================================


-- ============================================================
-- ENUMS
-- ============================================================
-- Using Postgres enums for all status fields.
-- Rationale: status values are fixed by business logic and change
-- only with deliberate migrations. Enums provide type safety and
-- clear documentation of allowed values.
-- Catalog values (technician types, license codes, etc.) are in
-- catalog tables instead so they can be extended without migrations.
-- ============================================================

CREATE TYPE app_role AS ENUM (
  'technician',
  'company_user',
  'admin'
);

CREATE TYPE user_status AS ENUM (
  'pending_verification',
  'active',
  'blocked',
  'suspended'
);

CREATE TYPE verification_status AS ENUM (
  'pending',
  'verified',
  'rejected'
);

CREATE TYPE document_status AS ENUM (
  'pending',
  'verified',
  'rejected',
  'expired'
);

CREATE TYPE offer_request_status AS ENUM (
  'pending',
  'accepted',
  'rejected',
  'expired',    -- set server-side when offer expires without a response
  'withdrawn'   -- voluntary cancellation by the initiating party
);

CREATE TYPE offer_status AS ENUM (
  'draft',
  'published',
  'closed',
  'expired'
);

CREATE TYPE company_member_role AS ENUM (
  'admin',
  'recruiter',
  'viewer'
);

CREATE TYPE experience_unit AS ENUM (
  'hours',
  'years'
);

CREATE TYPE sender_role AS ENUM (
  'technician',
  'company'
);

CREATE TYPE activity_type AS ENUM (
  'application_received',
  'application_accepted',
  'application_rejected',
  'direct_offer_received',
  'direct_offer_accepted',
  'direct_offer_rejected',
  'chat_message_received'
);

CREATE TYPE activity_recipient_scope AS ENUM (
  'technician',
  'company'
);

CREATE TYPE activity_entity_type AS ENUM (
  'offer_request',
  'offer_application',
  'chat_message'
);


-- ============================================================
-- CATALOG TABLES
-- ============================================================
-- Reference data managed by admin. Using text codes as PKs
-- so foreign key values are self-documenting in queries.
-- ============================================================

CREATE TABLE technician_types (
  code            TEXT    PRIMARY KEY,
  label           TEXT    NOT NULL,
  requires_license BOOLEAN NOT NULL DEFAULT false,
  is_active       BOOLEAN NOT NULL DEFAULT true,
  sort_order      INT     NOT NULL DEFAULT 0
);

CREATE TABLE license_categories (
  code            TEXT    PRIMARY KEY,
  label           TEXT    NOT NULL,
  category_group  TEXT    NOT NULL, -- 'A', 'B1', 'B2', 'B3', 'L', 'C'
  sort_order      INT     NOT NULL DEFAULT 0
);

CREATE TABLE aircraft_types (
  code              TEXT    PRIMARY KEY,
  label             TEXT    NOT NULL,
  manufacturer      TEXT,
  aircraft_family   TEXT,
  aircraft_category TEXT    NOT NULL CHECK (aircraft_category IN ('airplane', 'helicopter')),
  is_active         BOOLEAN NOT NULL DEFAULT true
);

CREATE TABLE company_types (
  code            TEXT    PRIMARY KEY,
  label           TEXT    NOT NULL,
  sort_order      INT     NOT NULL DEFAULT 0
);

CREATE TABLE contract_types (
  code            TEXT    PRIMARY KEY,
  label           TEXT    NOT NULL,
  sort_order      INT     NOT NULL DEFAULT 0
);


-- ============================================================
-- CATALOG SEEDS
-- ============================================================

INSERT INTO technician_types (code, label, requires_license, is_active, sort_order) VALUES
  ('mechanic',           'Mechanic (Part-66 A / B1)',        true,  true,  1),
  ('avionic',            'Avionics Technician (Part-66 B2)', true,  true,  2),
  ('sheet_metal_worker', 'Sheet Metal Worker',                false, true,  3),
  ('painter',            'Aircraft Painter',                  false, true,  4),
  ('composite',          'Composite Technician',              false, true,  5),
  -- Pilot: exists in model, inactive in V2 UI
  ('pilot',              'Pilot',                             true,  false, 6);

INSERT INTO license_categories (code, label, category_group, sort_order) VALUES
  ('A1',   'A1 — Line Maintenance (Aeroplanes Turbine)',    'A',  1),
  ('A2',   'A2 — Line Maintenance (Aeroplanes Piston)',     'A',  2),
  ('A3',   'A3 — Line Maintenance (Helicopters Turbine)',   'A',  3),
  ('A4',   'A4 — Line Maintenance (Helicopters Piston)',    'A',  4),
  ('B1.1', 'B1.1 — Turbine-powered Aeroplanes',             'B1', 5),
  ('B1.2', 'B1.2 — Piston-powered Aeroplanes',              'B1', 6),
  ('B1.3', 'B1.3 — Turbine-powered Helicopters',            'B1', 7),
  ('B1.4', 'B1.4 — Piston-powered Helicopters',             'B1', 8),
  ('B2',   'B2 — Avionics',                                 'B2', 9),
  ('B2L',  'B2L — Limited Avionics',                        'B2', 10),
  ('B3',   'B3 — Light Aircraft Piston',                    'B3', 11),
  ('L',    'L — Light Aircraft',                            'L',  12),
  ('C',    'C — Base Maintenance',                          'C',  13);

-- MVP catalog note: Aircraft type codes are intentionally simplified.
-- One code per aircraft family (e.g. B737 covers all 737 variants; H135 replaces EC135).
-- More granular variant codes (B737NG, B737CL, EC135) can be added in a later migration
-- if clients need them. Codes here must match src/constants/aircraftTypes.ts exactly.
INSERT INTO aircraft_types (code, label, manufacturer, aircraft_family, aircraft_category, is_active) VALUES
  -- Airbus — narrow-body
  ('A220',  'Airbus A220',           'Airbus',             'narrow_body', 'airplane',   true),
  ('A318',  'Airbus A318',           'Airbus',             'narrow_body', 'airplane',   true),
  ('A319',  'Airbus A319',           'Airbus',             'narrow_body', 'airplane',   true),
  ('A320',  'Airbus A320',           'Airbus',             'narrow_body', 'airplane',   true),
  ('A321',  'Airbus A321',           'Airbus',             'narrow_body', 'airplane',   true),
  -- Airbus — wide-body
  ('A330',  'Airbus A330',           'Airbus',             'wide_body',   'airplane',   true),
  ('A340',  'Airbus A340',           'Airbus',             'wide_body',   'airplane',   true),
  ('A350',  'Airbus A350 XWB',       'Airbus',             'wide_body',   'airplane',   true),
  ('A380',  'Airbus A380',           'Airbus',             'wide_body',   'airplane',   true),
  -- Boeing — narrow-body
  ('B737',  'Boeing 737',            'Boeing',             'narrow_body', 'airplane',   true),
  ('B757',  'Boeing 757',            'Boeing',             'narrow_body', 'airplane',   true),
  -- Boeing — wide-body
  ('B747',  'Boeing 747',            'Boeing',             'wide_body',   'airplane',   true),
  ('B767',  'Boeing 767',            'Boeing',             'wide_body',   'airplane',   true),
  ('B777',  'Boeing 777',            'Boeing',             'wide_body',   'airplane',   true),
  ('B787',  'Boeing 787 Dreamliner', 'Boeing',             'wide_body',   'airplane',   true),
  -- Turboprops
  ('ATR42', 'ATR 42',                'ATR',                'turboprop',   'airplane',   true),
  ('ATR72', 'ATR 72',                'ATR',                'turboprop',   'airplane',   true),
  ('Q400',  'Bombardier Q400',       'Bombardier',         'turboprop',   'airplane',   true),
  -- Bombardier regional jets
  ('CRJ200','Bombardier CRJ-200',    'Bombardier',         'narrow_body', 'airplane',   true),
  ('CRJ700','Bombardier CRJ-700',    'Bombardier',         'narrow_body', 'airplane',   true),
  ('CRJ900','Bombardier CRJ-900',    'Bombardier',         'narrow_body', 'airplane',   true),
  -- Embraer regional jets
  ('E175',  'Embraer E175',          'Embraer',            'narrow_body', 'airplane',   true),
  ('E190',  'Embraer E190',          'Embraer',            'narrow_body', 'airplane',   true),
  ('E195',  'Embraer E195',          'Embraer',            'narrow_body', 'airplane',   true),
  -- Airbus Helicopters
  ('H125',  'Airbus H125',           'Airbus Helicopters', 'helicopter',  'helicopter', true),
  ('H135',  'Airbus H135',           'Airbus Helicopters', 'helicopter',  'helicopter', true),
  ('H145',  'Airbus H145',           'Airbus Helicopters', 'helicopter',  'helicopter', true),
  -- Sikorsky
  ('S76',   'Sikorsky S-76',         'Sikorsky',           'helicopter',  'helicopter', true),
  ('S92',   'Sikorsky S-92',         'Sikorsky',           'helicopter',  'helicopter', true),
  -- Bell
  ('B407',  'Bell 407',              'Bell',               'helicopter',  'helicopter', true),
  ('B412',  'Bell 412',              'Bell',               'helicopter',  'helicopter', true),
  -- Leonardo / Robinson
  ('AW139', 'Leonardo AW139',        'Leonardo',           'helicopter',  'helicopter', true),
  ('R44',   'Robinson R44',          'Robinson',           'helicopter',  'helicopter', true);

INSERT INTO company_types (code, label, sort_order) VALUES
  ('MRO',                 'MRO (Maintenance, Repair & Overhaul)', 1),
  ('airline',             'Airline',                               2),
  ('recruitment_agency',  'Recruitment Agency',                    3),
  ('helicopter_operator', 'Helicopter Operator',                   4),
  ('other',               'Other',                                 5);

INSERT INTO contract_types (code, label, sort_order) VALUES
  ('permanent',  'Permanent',  1),
  ('long_term',  'Long Term',  2),
  ('short_term', 'Short Term', 3);


-- ============================================================
-- BASE TABLES
-- ============================================================

-- profiles
-- Bridge between auth.users and app-level roles.
-- One row per authenticated user. id = auth.users.id.
CREATE TABLE profiles (
  id         UUID         PRIMARY KEY, -- = auth.users.id
  role       app_role     NOT NULL,    -- SERVER-ASSIGNED: set by auth trigger on registration; admin-only after
  status     user_status  NOT NULL DEFAULT 'pending_verification', -- SERVER-MANAGED: set by admin; not user-editable
  created_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- Canonical location catalog used by technicians, companies and offers.
-- MVP seed is curated, not a complete worldwide airport database.
-- Add new airport rows later without changing schema.
CREATE TABLE location_airports (
  id           TEXT             PRIMARY KEY, -- e.g. airport:LEVC
  country_name TEXT             NOT NULL,
  city         TEXT             NOT NULL,
  airport      TEXT             NOT NULL,
  icao         TEXT             NOT NULL UNIQUE,
  iata         TEXT,
  latitude     DOUBLE PRECISION NOT NULL,
  longitude    DOUBLE PRECISION NOT NULL,
  is_active    BOOLEAN          NOT NULL DEFAULT true
);


-- ============================================================
-- TECHNICIAN TABLES
-- ============================================================

-- IMPORTANT: Companies must NEVER query technician_profiles directly.
-- All company-facing technician queries must go through technician_public_view (defined in RLS_PLAN_V2.md).
-- The view enforces column-level privacy via CASE WHEN offer_accepted_between().
CREATE TABLE technician_profiles (
  id                   UUID                PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id              UUID                NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  anonymous_code       TEXT                NOT NULL UNIQUE,

  -- Private fields (hidden until offer accepted)
  first_name           TEXT                NOT NULL,
  last_name            TEXT                NOT NULL,
  email                TEXT                NOT NULL,
  phone                TEXT,
  birth_date           DATE                NOT NULL,

  -- Public professional fields
  technician_type      TEXT                NOT NULL REFERENCES technician_types(code),
  location_city_id     TEXT                NOT NULL REFERENCES location_airports(id),

  -- Availability as JSONB: { immediately, available_from, contract_types[] }
  availability         JSONB               NOT NULL DEFAULT '{"immediately": false, "available_from": null, "contract_types": []}',

  -- Status — verification_status is ADMIN-ONLY; technician cannot write this field
  verification_status  verification_status NOT NULL DEFAULT 'pending',
  profile_completeness INT                 NOT NULL DEFAULT 0 CHECK (profile_completeness BETWEEN 0 AND 100),

  -- Optional private fields
  social_links         JSONB,

  created_at           TIMESTAMPTZ         NOT NULL DEFAULT now(),
  updated_at           TIMESTAMPTZ         NOT NULL DEFAULT now()
);

CREATE TABLE technician_licenses (
  id             UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  technician_id  UUID        NOT NULL REFERENCES technician_profiles(id) ON DELETE CASCADE,
  license_code   TEXT        NOT NULL REFERENCES license_categories(code),
  issued_at      DATE,
  expires_at     DATE,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (technician_id, license_code)
);

CREATE TABLE technician_habilitations (
  id                  UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  technician_id       UUID        NOT NULL REFERENCES technician_profiles(id) ON DELETE CASCADE,
  license_code        TEXT        NOT NULL REFERENCES license_categories(code),
  aircraft_type_code  TEXT        NOT NULL REFERENCES aircraft_types(code),
  issued_at           DATE,
  expires_at          DATE,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (technician_id, license_code, aircraft_type_code)
);

CREATE TABLE technician_aircraft_experience (
  id                  UUID             PRIMARY KEY DEFAULT gen_random_uuid(),
  technician_id       UUID             NOT NULL REFERENCES technician_profiles(id) ON DELETE CASCADE,
  -- aircraft_type_code must reference aircraft_types.code. No generic/fallback codes (e.g. 'GENERAL') allowed.
  aircraft_type_code  TEXT             NOT NULL REFERENCES aircraft_types(code),
  value               DOUBLE PRECISION NOT NULL CHECK (value >= 0),
  unit                experience_unit  NOT NULL,
  created_at          TIMESTAMPTZ      NOT NULL DEFAULT now(),
  UNIQUE (technician_id, aircraft_type_code)
);

-- MVP review model: admin manually sets status. No audit log, no auto-expiration, no reviewer id.
-- Add reviewed_by / audit table / cron trigger later only if real users need them.
CREATE TABLE documents (
  id               UUID             PRIMARY KEY DEFAULT gen_random_uuid(),
  technician_id    UUID             NOT NULL REFERENCES technician_profiles(id) ON DELETE CASCADE,
  type             TEXT             NOT NULL,  -- 'license' | 'medical' | 'id' | 'training' | 'resume' | 'other'
  file_name        TEXT             NOT NULL,
  storage_path     TEXT             NOT NULL,  -- local path in demo; Supabase Storage path later
  status           document_status  NOT NULL DEFAULT 'pending',
  uploaded_at      TIMESTAMPTZ      NOT NULL DEFAULT now(),
  reviewed_at      TIMESTAMPTZ,                -- set when admin changes status; cleared on reset to pending
  rejection_reason TEXT,                       -- set when rejected; cleared on all other transitions
  expires_at       TIMESTAMPTZ                 -- for licenses and time-limited certificates
);


-- ============================================================
-- COMPANY TABLES
-- ============================================================

CREATE TABLE companies (
  id                  UUID                PRIMARY KEY DEFAULT gen_random_uuid(),
  name                TEXT                NOT NULL,
  location_city_id    TEXT                NOT NULL REFERENCES location_airports(id),
  phone               TEXT,
  email               TEXT                NOT NULL,
  company_type        TEXT                NOT NULL REFERENCES company_types(code),
  verification_status verification_status NOT NULL DEFAULT 'pending', -- ADMIN-ONLY; company cannot write this
  created_at          TIMESTAMPTZ         NOT NULL DEFAULT now(),
  updated_at          TIMESTAMPTZ         NOT NULL DEFAULT now()
);

-- Company members are created manually in the MVP.
-- No self-service invitations, invite tokens, or email invite flows.
CREATE TABLE company_members (
  id          UUID                PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id  UUID                NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  user_id     UUID                NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  role        company_member_role NOT NULL DEFAULT 'viewer',
  created_at  TIMESTAMPTZ         NOT NULL DEFAULT now(),
  UNIQUE (company_id, user_id),
  -- MVP: one company per company user. Multi-company membership is future scope.
  UNIQUE (user_id)
);


-- ============================================================
-- OFFERS
-- ============================================================

CREATE TABLE offers (
  id                    UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id            UUID          NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  title                 TEXT          NOT NULL,
  description           TEXT          NOT NULL,
  contract_type         TEXT          NOT NULL REFERENCES contract_types(code),
  location_city_id      TEXT          NOT NULL REFERENCES location_airports(id),
  -- Controlled snapshot copied from location_airports on create/update.
  location_country      TEXT          NOT NULL,
  location_city         TEXT          NOT NULL,
  location_base_airport TEXT          NOT NULL,
  min_years_experience  INT           NOT NULL DEFAULT 0 CHECK (min_years_experience >= 0),
  status                offer_status  NOT NULL DEFAULT 'draft',
  visible               BOOLEAN       NOT NULL DEFAULT false,
  expires_at            TIMESTAMPTZ,
  created_at            TIMESTAMPTZ   NOT NULL DEFAULT now(),
  updated_at            TIMESTAMPTZ   NOT NULL DEFAULT now()
);

-- Required technician types for an offer (optional — no rows = any type accepted)
-- Composite PK (offer_id, technician_type_code) — no surrogate id column.
-- Local demo seeds include a local `id` field (e.g. "ort-001") for demo readability only.
-- Drop the local id field when inserting into Supabase; use (offer_id, technician_type_code) pairs.
CREATE TABLE offer_required_technician_types (
  offer_id             UUID NOT NULL REFERENCES offers(id) ON DELETE CASCADE,
  technician_type_code TEXT NOT NULL REFERENCES technician_types(code),
  PRIMARY KEY (offer_id, technician_type_code)
);

-- Required licenses for an offer (optional)
-- Composite PK (offer_id, license_code) — no surrogate id column.
-- Local demo seeds include a local `id` field for demo readability only.
CREATE TABLE offer_required_licenses (
  offer_id     UUID NOT NULL REFERENCES offers(id) ON DELETE CASCADE,
  license_code TEXT NOT NULL REFERENCES license_categories(code),
  PRIMARY KEY (offer_id, license_code)
);

-- Required aircraft types for an offer (optional)
-- Composite PK (offer_id, aircraft_type_code) — no surrogate id column.
-- Local demo seeds include a local `id` field for demo readability only.
CREATE TABLE offer_required_aircraft_types (
  offer_id            UUID NOT NULL REFERENCES offers(id) ON DELETE CASCADE,
  aircraft_type_code  TEXT NOT NULL REFERENCES aircraft_types(code),
  PRIMARY KEY (offer_id, aircraft_type_code)
);


-- ============================================================
-- OFFER REQUESTS
-- Company sends a direct offer to a specific technician.
-- ============================================================

CREATE TABLE offer_requests (
  id                  UUID                 PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id          UUID                 NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  technician_id       UUID                 NOT NULL REFERENCES technician_profiles(id) ON DELETE CASCADE,
  offer_id            UUID                 REFERENCES offers(id) ON DELETE SET NULL,
  status              offer_request_status NOT NULL DEFAULT 'pending',
  -- READ-ONLY: set exclusively by handle_offer_accepted trigger, never by client
  identity_revealed   BOOLEAN              NOT NULL DEFAULT false,
  -- READ-ONLY: set exclusively by handle_offer_accepted trigger, never by client
  documents_unlocked  BOOLEAN              NOT NULL DEFAULT false,
  message             TEXT,
  created_at          TIMESTAMPTZ          NOT NULL DEFAULT now(),
  updated_at          TIMESTAMPTZ          NOT NULL DEFAULT now()
);


-- ============================================================
-- OFFER APPLICATIONS
-- Technician applies to a published offer.
-- ============================================================

CREATE TABLE offer_applications (
  id                  UUID                 PRIMARY KEY DEFAULT gen_random_uuid(),
  technician_id       UUID                 NOT NULL REFERENCES technician_profiles(id) ON DELETE CASCADE,
  offer_id            UUID                 NOT NULL REFERENCES offers(id) ON DELETE CASCADE,
  company_id          UUID                 NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  status              offer_request_status NOT NULL DEFAULT 'pending',
  -- READ-ONLY: set exclusively by handle_offer_accepted trigger, never by client
  identity_revealed   BOOLEAN              NOT NULL DEFAULT false,
  -- READ-ONLY: set exclusively by handle_offer_accepted trigger, never by client
  documents_unlocked  BOOLEAN              NOT NULL DEFAULT false,
  cover_note          TEXT,
  created_at          TIMESTAMPTZ          NOT NULL DEFAULT now(),
  updated_at          TIMESTAMPTZ          NOT NULL DEFAULT now(),
  -- One application per technician per offer, regardless of status.
  -- Reapplication (after withdrawn/rejected/expired) is out of scope for MVP.
  UNIQUE (technician_id, offer_id)
);


-- ============================================================
-- CHAT
-- Chat rooms are created only on acceptance.
-- ============================================================

CREATE TABLE chat_rooms (
  id                    UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  offer_request_id      UUID        REFERENCES offer_requests(id) ON DELETE CASCADE,
  offer_application_id  UUID        REFERENCES offer_applications(id) ON DELETE CASCADE,
  technician_id         UUID        NOT NULL REFERENCES technician_profiles(id) ON DELETE CASCADE,
  company_id            UUID        NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
  -- Exactly one source must be set
  CONSTRAINT check_single_source CHECK (
    (offer_request_id IS NOT NULL AND offer_application_id IS NULL) OR
    (offer_request_id IS NULL AND offer_application_id IS NOT NULL)
  )
);

-- Enforce one chat room per offer_request (NULLs excluded)
CREATE UNIQUE INDEX idx_chat_rooms_offer_request
  ON chat_rooms(offer_request_id)
  WHERE offer_request_id IS NOT NULL;

-- Enforce one chat room per offer_application (NULLs excluded)
CREATE UNIQUE INDEX idx_chat_rooms_offer_application
  ON chat_rooms(offer_application_id)
  WHERE offer_application_id IS NOT NULL;

CREATE TABLE chat_messages (
  id                       UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  chat_room_id             UUID        NOT NULL REFERENCES chat_rooms(id) ON DELETE CASCADE,
  sender_user_id           UUID        NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  sender_company_member_id UUID        REFERENCES company_members(id) ON DELETE SET NULL,
  sender_role              sender_role NOT NULL,
  body                     TEXT        NOT NULL,
  sent_at                  TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT chat_messages_company_member_role CHECK (
    sender_company_member_id IS NULL OR sender_role = 'company'
  )
);


-- ============================================================
-- ACTIVITY / NOTIFICATION TABLES
-- ============================================================

CREATE TABLE activity_events (
  id                       UUID                      PRIMARY KEY DEFAULT gen_random_uuid(),
  type                     activity_type             NOT NULL,
  recipient_scope          activity_recipient_scope  NOT NULL,
  recipient_technician_id  UUID                      REFERENCES technician_profiles(id) ON DELETE CASCADE,
  recipient_company_id     UUID                      REFERENCES companies(id) ON DELETE CASCADE,
  actor_profile_id         UUID                      REFERENCES profiles(id) ON DELETE SET NULL,
  entity_type              activity_entity_type      NOT NULL,
  entity_id                UUID                      NOT NULL,
  offer_id                 UUID                      REFERENCES offers(id) ON DELETE SET NULL,
  metadata                 JSONB                     NOT NULL DEFAULT '{}'::jsonb,
  created_at               TIMESTAMPTZ               NOT NULL DEFAULT now(),
  CONSTRAINT activity_events_recipient_check CHECK (
    (
      recipient_scope = 'technician'
      AND recipient_technician_id IS NOT NULL
      AND recipient_company_id IS NULL
    )
    OR
    (
      recipient_scope = 'company'
      AND recipient_company_id IS NOT NULL
      AND recipient_technician_id IS NULL
    )
  )
);

CREATE TABLE activity_reads (
  activity_event_id UUID        NOT NULL REFERENCES activity_events(id) ON DELETE CASCADE,
  profile_id        UUID        NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  read_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (activity_event_id, profile_id)
);


-- ============================================================
-- INDEXES
-- ============================================================

-- Technician search
CREATE INDEX idx_technician_profiles_user_id         ON technician_profiles(user_id);
CREATE INDEX idx_technician_profiles_type            ON technician_profiles(technician_type);
CREATE INDEX idx_technician_profiles_verification    ON technician_profiles(verification_status);
CREATE INDEX idx_technician_profiles_location_city   ON technician_profiles(location_city_id);

-- Location catalog
CREATE INDEX idx_location_airports_country_city      ON location_airports(country_name, city);
CREATE INDEX idx_location_airports_iata              ON location_airports(iata);

-- Licenses / habilitations / experience
CREATE INDEX idx_technician_licenses_technician      ON technician_licenses(technician_id);
CREATE INDEX idx_technician_licenses_code            ON technician_licenses(license_code);
CREATE INDEX idx_technician_habilitations_technician ON technician_habilitations(technician_id);
CREATE INDEX idx_aircraft_experience_technician      ON technician_aircraft_experience(technician_id);

-- Documents
CREATE INDEX idx_documents_technician                ON documents(technician_id);
CREATE INDEX idx_documents_status                    ON documents(status);

-- Companies
CREATE INDEX idx_companies_location_city             ON companies(location_city_id);
CREATE INDEX idx_company_members_company             ON company_members(company_id);
CREATE INDEX idx_company_members_user                ON company_members(user_id);

-- Offers
CREATE INDEX idx_offers_company                      ON offers(company_id);
CREATE INDEX idx_offers_status_visible               ON offers(status, visible);
CREATE INDEX idx_offers_contract_type                ON offers(contract_type);
CREATE INDEX idx_offers_location_city                ON offers(location_city_id);

-- Offer requests
CREATE INDEX idx_offer_requests_company              ON offer_requests(company_id);
CREATE INDEX idx_offer_requests_technician           ON offer_requests(technician_id);
CREATE INDEX idx_offer_requests_status               ON offer_requests(status);

-- Offer applications
CREATE INDEX idx_offer_applications_technician       ON offer_applications(technician_id);
CREATE INDEX idx_offer_applications_offer            ON offer_applications(offer_id);
CREATE INDEX idx_offer_applications_company          ON offer_applications(company_id);
CREATE INDEX idx_offer_applications_status           ON offer_applications(status);

-- Chat
CREATE INDEX idx_chat_rooms_technician               ON chat_rooms(technician_id);
CREATE INDEX idx_chat_rooms_company                  ON chat_rooms(company_id);
CREATE INDEX idx_chat_messages_room_sent             ON chat_messages(chat_room_id, sent_at);

-- Activity / notifications
CREATE INDEX idx_activity_events_technician_created   ON activity_events(recipient_technician_id, created_at DESC);
CREATE INDEX idx_activity_events_company_created      ON activity_events(recipient_company_id, created_at DESC);
CREATE INDEX idx_activity_events_entity               ON activity_events(entity_type, entity_id);
CREATE INDEX idx_activity_events_offer                ON activity_events(offer_id);
CREATE INDEX idx_activity_reads_profile               ON activity_reads(profile_id);


-- ============================================================
-- HELPER FUNCTION: compute age from birth_date
-- Used in RLS views to expose age without exposing birth_date.
-- ============================================================

CREATE OR REPLACE FUNCTION compute_age(birth_date DATE)
RETURNS INT
LANGUAGE SQL
IMMUTABLE
AS $$
  SELECT DATE_PART('year', AGE(CURRENT_DATE, birth_date))::INT
$$;


-- ============================================================
-- NOTES
-- ============================================================
-- 1. Triggers for on_offer_accepted (set identity_revealed,
--    documents_unlocked, create chat_room) are planned but not
--    included here. They belong in a migrations file once
--    Supabase is connected.
--
-- 2. RLS policies are designed in docs/RLS_PLAN_V2.md and will
--    be added separately per table during Phase V2-S1.
--
-- 3. Storage bucket 'technician-documents' is provisioned
--    separately in Supabase. Path: {technician_id}/{document_id}/{file_name}
-- ============================================================
